// <auto-generated />
using System;
using DocumentProcessorDB;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace DocumentProcessorDB.Migrations
{
    [DbContext(typeof(DocumentProcessorContext))]
    [Migration("20240704155904_addnullablecolumns")]
    partial class addnullablecolumns
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.6")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("DocumentProcessorDB.Models.FileDetails", b =>
                {
                    b.Property<Guid>("FileId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("ErrorMessage")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("FolderDetailsId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("SourceFileName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<byte>("Status")
                        .HasColumnType("tinyint");

                    b.HasKey("FileId");

                    b.HasIndex("FolderDetailsId");

                    b.ToTable("FileDetails");
                });

            modelBuilder.Entity("DocumentProcessorDB.Models.FolderDetails", b =>
                {
                    b.Property<Guid>("FolderId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("DestinationSubFolderName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ErrorMessage")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MergedFileName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SourceSubFolderName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<byte>("Status")
                        .HasColumnType("tinyint");

                    b.Property<Guid>("WorkerId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("FolderId");

                    b.HasIndex("WorkerId");

                    b.ToTable("FolderDetails");
                });

            modelBuilder.Entity("DocumentProcessorDB.Models.TaskManager", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<string>("CaseNumber")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime>("CreatedOn")
                        .HasColumnType("datetime2");

                    b.Property<string>("LockedBy")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("ModifiedBy")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime?>("ModifiedOn")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("ReleaseOn")
                        .HasColumnType("datetime2");

                    b.Property<int?>("SPID")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("TaskManager");
                });

            modelBuilder.Entity("DocumentProcessorDB.Models.WorkerNode", b =>
                {
                    b.Property<Guid>("WorkerID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("LastActiveDateTime")
                        .HasColumnType("datetime2");

                    b.Property<byte>("Status")
                        .HasColumnType("tinyint");

                    b.Property<DateTime>("TaskAssignedDateTime")
                        .HasColumnType("datetime2");

                    b.Property<string>("WorkingFolderName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("WorkerID");

                    b.ToTable("WorkerNode");
                });

            modelBuilder.Entity("DocumentProcessorDB.Models.FileDetails", b =>
                {
                    b.HasOne("DocumentProcessorDB.Models.FolderDetails", "FolderDetails")
                        .WithMany("FileDetails")
                        .HasForeignKey("FolderDetailsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("FolderDetails");
                });

            modelBuilder.Entity("DocumentProcessorDB.Models.FolderDetails", b =>
                {
                    b.HasOne("DocumentProcessorDB.Models.WorkerNode", "WorkerNode")
                        .WithMany("FolderDetails")
                        .HasForeignKey("WorkerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("WorkerNode");
                });

            modelBuilder.Entity("DocumentProcessorDB.Models.FolderDetails", b =>
                {
                    b.Navigation("FileDetails");
                });

            modelBuilder.Entity("DocumentProcessorDB.Models.WorkerNode", b =>
                {
                    b.Navigation("FolderDetails");
                });
#pragma warning restore 612, 618
        }
    }
}
